In [1]:
import numpy as np

In [2]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [5]:
# no hidden layer weights
weights = 2* np.random.random((2, 1))-1 
bias = 2 * np.random.random(1) - 1
weights, bias

(array([[-0.5300117 ],
        [ 0.83892213]]),
 array([0.52000544]))

In [5]:
# forward propagation without any hidden layer
output0 = X
output = sig(np.dot(output0, weights) + bias)
output

array([[0.38449744],
       [0.61011274],
       [0.24518281],
       [0.448636  ]])